# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewer_v1_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

global label_text 
label_text = "Hello"

from PyQt5 import QtCore, QtGui, QtWidgets
import glob
import os

def filenames_from_cat(top,second):
    cats_globs = glob.glob('./*/*/*.cats')
    matches = []
    print(glob.glob('*'))
    for g in cats_globs:
        with open(g) as file:
            for line in file:
                line = line.split()[0]
                line = line.split(",")
                if int(line[0]) == top and int(line[1]) == second:
                    dir = os.path.basename(g)
                    filename = os.path.splitext(dir)[0]
                    matches.append(filename)
    
    return matches

def save_email_from_filename(filename):
    full_filename = glob.glob('./*/*/' + str(filename) + '.txt')
    email_contents = ""
    with open(full_filename[0]) as file:
        for line in file:
            email_contents = email_contents + line
    return email_contents

def save_all_from_cat(primary, secondary):
    filenames = filenames_from_cat(primary, secondary)
    contents = ""
    for file in filenames:
        contents = contents + save_email_from_filename(file)
        contents = contents + "\n" + ("*" * 100) + "\n\n"
    
    global label_text
    label_text = contents
    

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(456, 397)
        MainWindow.setWindowIcon(QtGui.QIcon('enron_logo.png'))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        
        self.label_text = "Hello"
        ################
        # Welcome page #
        ################

        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()

        self.pushButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1))
        
        #########################
        # Primary category page #
        #########################
        self.page_2.setObjectName("page_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.radioButton = QtWidgets.QRadioButton(self.page_2)
        self.radioButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(2))

        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_3.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.page_2)

        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_3.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.page_2)
        self.radioButton_2.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(3))


        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_3.addWidget(self.radioButton_3)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.radioButton_3.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(4))


        #####################
        # Coarse genre page #
        #####################

        self.page_3.setObjectName("page_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.page_3)

        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_4.addWidget(self.radioButton_4)
        self.radioButton_4.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(5))

        self.radioButton_5 = QtWidgets.QRadioButton(self.page_3)
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_5.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_5.clicked.connect(lambda: save_all_from_cat(1,2))
        self.radioButton_5.clicked.connect(lambda: self.label_7.setText(label_text))
        self.verticalLayout_4.addWidget(self.radioButton_5)

        self.radioButton_6 = QtWidgets.QRadioButton(self.page_3)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_4.addWidget(self.radioButton_6)
        self.radioButton_6.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_6.clicked.connect(lambda: save_all_from_cat(1,3))
        self.radioButton_6.clicked.connect(lambda: self.label_7.setText(label_text))

        self.radioButton_7 = QtWidgets.QRadioButton(self.page_3)
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_7.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_7.clicked.connect(lambda: save_all_from_cat(1,4))
        self.radioButton_7.clicked.connect(lambda: self.label_7.setText(label_text))
        self.verticalLayout_4.addWidget(self.radioButton_7)

        self.radioButton_8 = QtWidgets.QRadioButton(self.page_3)
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_8.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_8.clicked.connect(lambda: save_all_from_cat(1,5))
        self.radioButton_8.clicked.connect(lambda: self.label_7.setText(label_text))
        self.verticalLayout_4.addWidget(self.radioButton_8)

        self.radioButton_9 = QtWidgets.QRadioButton(self.page_3)
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_9.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_9.clicked.connect(lambda: save_all_from_cat(1,6))
        self.radioButton_9.clicked.connect(lambda: self.label_7.setText(label_text))
        self.verticalLayout_4.addWidget(self.radioButton_9)

        self.radioButton_10 = QtWidgets.QRadioButton(self.page_3)
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioButton_10.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_10.clicked.connect(lambda: save_all_from_cat(1,7))
        self.radioButton_10.clicked.connect(lambda: self.label_7.setText(label_text))
        self.verticalLayout_4.addWidget(self.radioButton_10)

        self.radioButton_11 = QtWidgets.QRadioButton(self.page_3)
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_11.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_11.clicked.connect(lambda: save_all_from_cat(1,8))
        self.radioButton_11.clicked.connect(lambda: self.label_7.setText(label_text))
        self.verticalLayout_4.addWidget(self.radioButton_11)

        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()

        #########################################
        # Included / forwarded information page #
        #########################################

        self.page_4.setObjectName("page_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.verticalLayout_5.addWidget(self.label_4)
        self.radioButton_12 = QtWidgets.QRadioButton(self.page_4)
        self.radioButton_12.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_12.clicked.connect(lambda: save_all_from_cat(2,1))
        self.radioButton_12.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_12.setObjectName("radioButton_12")

        self.verticalLayout_5.addWidget(self.radioButton_12)
        self.radioButton_13 = QtWidgets.QRadioButton(self.page_4)
        self.radioButton_13.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_13.clicked.connect(lambda: save_all_from_cat(2,2))
        self.radioButton_13.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_13.setObjectName("radioButton_13")

        self.verticalLayout_5.addWidget(self.radioButton_13)
        self.radioButton_14 = QtWidgets.QRadioButton(self.page_4)
        self.radioButton_14.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_14.clicked.connect(lambda: save_all_from_cat(2,3))
        self.radioButton_14.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_14.setObjectName("radioButton_14")

        self.verticalLayout_5.addWidget(self.radioButton_14)
        self.radioButton_15 = QtWidgets.QRadioButton(self.page_4)
        self.radioButton_15.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_15.clicked.connect(lambda: save_all_from_cat(2,4))
        self.radioButton_15.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_15.setObjectName("radioButton_15")

        self.verticalLayout_5.addWidget(self.radioButton_15)
        self.radioButton_16 = QtWidgets.QRadioButton(self.page_4)
        self.radioButton_16.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_16.clicked.connect(lambda: save_all_from_cat(2,5))
        self.radioButton_16.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_16.setObjectName("radioButton_16")

        self.verticalLayout_5.addWidget(self.radioButton_16)
        self.radioButton_17 = QtWidgets.QRadioButton(self.page_4)
        self.radioButton_17.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_17.clicked.connect(lambda: save_all_from_cat(2,6))
        self.radioButton_17.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_17.setObjectName("radioButton_17")

        self.verticalLayout_5.addWidget(self.radioButton_17)
        self.radioButton_18 = QtWidgets.QRadioButton(self.page_4)
        self.radioButton_18.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_18.clicked.connect(lambda: save_all_from_cat(2,7))
        self.radioButton_18.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_18.setObjectName("radioButton_18")

        self.verticalLayout_5.addWidget(self.radioButton_18)
        self.radioButton_19 = QtWidgets.QRadioButton(self.page_4)
        self.radioButton_19.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_19.clicked.connect(lambda: save_all_from_cat(2,8))
        self.radioButton_19.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_19.setObjectName("radioButton_19")

        self.verticalLayout_5.addWidget(self.radioButton_19)
        self.radioButton_20 = QtWidgets.QRadioButton(self.page_4)
        self.radioButton_20.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_20.clicked.connect(lambda: save_all_from_cat(2,9))
        self.radioButton_20.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_20.setObjectName("radioButton_20")

        self.verticalLayout_5.addWidget(self.radioButton_20)
        self.radioButton_21 = QtWidgets.QRadioButton(self.page_4)
        self.radioButton_21.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_21.clicked.connect(lambda: save_all_from_cat(2,10))
        self.radioButton_21.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_21.setObjectName("radioButton_21")

        self.verticalLayout_5.addWidget(self.radioButton_21)
        self.radioButton_22 = QtWidgets.QRadioButton(self.page_4)
        self.radioButton_22.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_22.clicked.connect(lambda: save_all_from_cat(2,11))
        self.radioButton_22.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_22.setObjectName("radioButton_22")

        self.verticalLayout_5.addWidget(self.radioButton_22)
        self.radioButton_23 = QtWidgets.QRadioButton(self.page_4)
        self.radioButton_23.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_23.clicked.connect(lambda: save_all_from_cat(2,12))
        self.radioButton_23.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_23.setObjectName("radioButton_23")

        self.verticalLayout_5.addWidget(self.radioButton_23)
        self.radioButton_24 = QtWidgets.QRadioButton(self.page_4)
        self.radioButton_24.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_24.clicked.connect(lambda: save_all_from_cat(2,13))
        self.radioButton_24.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_24.setObjectName("radioButton_24")

        self.verticalLayout_5.addWidget(self.radioButton_24)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()

        #######################
        # Emotional tone page #
        #######################

        self.page_5.setObjectName("page_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.verticalLayout_6.addWidget(self.label_5)
        self.radioButton_25 = QtWidgets.QRadioButton(self.page_5)
        self.radioButton_25.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_25.clicked.connect(lambda: save_all_from_cat(4,1))
        self.radioButton_25.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_25.setObjectName("radioButton_25")
        
        self.verticalLayout_6.addWidget(self.radioButton_25)
        self.radioButton_40 = QtWidgets.QRadioButton(self.page_5)
        self.radioButton_40.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_40.clicked.connect(lambda: save_all_from_cat(4,16))
        self.radioButton_40.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_40.setObjectName("radioButton_40")
        
        self.verticalLayout_6.addWidget(self.radioButton_40)
        self.radioButton_26 = QtWidgets.QRadioButton(self.page_5)
        self.radioButton_26.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_26.clicked.connect(lambda: save_all_from_cat(4,2))
        self.radioButton_26.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_26.setObjectName("radioButton_26")
        
        self.verticalLayout_6.addWidget(self.radioButton_26)
        self.radioButton_41 = QtWidgets.QRadioButton(self.page_5)
        self.radioButton_41.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_41.clicked.connect(lambda: save_all_from_cat(4,17))
        self.radioButton_41.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_41.setObjectName("radioButton_41")
        
        self.verticalLayout_6.addWidget(self.radioButton_41)
        self.radioButton_27 = QtWidgets.QRadioButton(self.page_5)
        self.radioButton_27.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_27.clicked.connect(lambda: save_all_from_cat(4,3))
        self.radioButton_27.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_27.setObjectName("radioButton_27")
        
        self.verticalLayout_6.addWidget(self.radioButton_27)
        self.radioButton_42 = QtWidgets.QRadioButton(self.page_5)
        self.radioButton_42.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_42.clicked.connect(lambda: save_all_from_cat(4,18))
        self.radioButton_42.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_42.setObjectName("radioButton_42")
        
        self.verticalLayout_6.addWidget(self.radioButton_42)
        self.radioButton_28 = QtWidgets.QRadioButton(self.page_5)
        self.radioButton_28.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_28.clicked.connect(lambda: save_all_from_cat(4,4))
        self.radioButton_28.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_28.setObjectName("radioButton_28")
        
        self.verticalLayout_6.addWidget(self.radioButton_28)
        self.radioButton_43 = QtWidgets.QRadioButton(self.page_5)
        self.radioButton_43.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_43.clicked.connect(lambda: save_all_from_cat(4,19))
        self.radioButton_43.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_43.setObjectName("radioButton_43")
        
        self.verticalLayout_6.addWidget(self.radioButton_43)
        self.radioButton_29 = QtWidgets.QRadioButton(self.page_5)
        self.radioButton_29.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_29.clicked.connect(lambda: save_all_from_cat(4,5))
        self.radioButton_29.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_29.setObjectName("radioButton_29")
        
        self.verticalLayout_6.addWidget(self.radioButton_29)
        self.radioButton_30 = QtWidgets.QRadioButton(self.page_5)
        self.radioButton_30.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_30.clicked.connect(lambda: save_all_from_cat(4,6))
        self.radioButton_30.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_30.setObjectName("radioButton_30")
        
        self.verticalLayout_6.addWidget(self.radioButton_30)
        self.radioButton_31 = QtWidgets.QRadioButton(self.page_5)
        self.radioButton_31.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_31.clicked.connect(lambda: save_all_from_cat(4,7))
        self.radioButton_31.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_31.setObjectName("radioButton_31")
        
        self.verticalLayout_6.addWidget(self.radioButton_31)
        self.radioButton_32 = QtWidgets.QRadioButton(self.page_5)
        self.radioButton_32.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_32.clicked.connect(lambda: save_all_from_cat(4,8))
        self.radioButton_32.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_32.setObjectName("radioButton_32")
        
        self.verticalLayout_6.addWidget(self.radioButton_32)
        self.radioButton_33 = QtWidgets.QRadioButton(self.page_5)
        self.radioButton_33.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_33.clicked.connect(lambda: save_all_from_cat(4,9))
        self.radioButton_33.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_33.setObjectName("radioButton_33")
        
        self.verticalLayout_6.addWidget(self.radioButton_33)
        self.radioButton_34 = QtWidgets.QRadioButton(self.page_5)
        self.radioButton_34.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_34.clicked.connect(lambda: save_all_from_cat(4,10))
        self.radioButton_34.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_34.setObjectName("radioButton_34")
        
        self.verticalLayout_6.addWidget(self.radioButton_34)
        self.radioButton_35 = QtWidgets.QRadioButton(self.page_5)
        self.radioButton_35.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_35.clicked.connect(lambda: save_all_from_cat(4,11))
        self.radioButton_35.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_35.setObjectName("radioButton_35")
        
        self.verticalLayout_6.addWidget(self.radioButton_35)
        self.radioButton_36 = QtWidgets.QRadioButton(self.page_5)
        self.radioButton_36.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_36.clicked.connect(lambda: save_all_from_cat(4,12))
        self.radioButton_36.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_36.setObjectName("radioButton_36")
        
        self.verticalLayout_6.addWidget(self.radioButton_36)
        self.radioButton_37 = QtWidgets.QRadioButton(self.page_5)
        self.radioButton_37.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_37.clicked.connect(lambda: save_all_from_cat(4,13))
        self.radioButton_37.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_37.setObjectName("radioButton_37")
        
        self.verticalLayout_6.addWidget(self.radioButton_37)
        self.radioButton_38 = QtWidgets.QRadioButton(self.page_5)
        self.radioButton_38.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_38.clicked.connect(lambda: save_all_from_cat(4,14))
        self.radioButton_38.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_38.setObjectName("radioButton_38")
        
        self.verticalLayout_6.addWidget(self.radioButton_38)
        self.radioButton_39 = QtWidgets.QRadioButton(self.page_5)
        self.radioButton_39.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_39.clicked.connect(lambda: save_all_from_cat(4,15))
        self.radioButton_39.clicked.connect(lambda: self.label_7.setText(label_text))
        self.radioButton_39.setObjectName("radioButton_39")
        
        self.verticalLayout_6.addWidget(self.radioButton_39)
        self.stackedWidget.addWidget(self.page_5)

        ########################################
        # Company business, strategy, etc page #
        ########################################
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)

        self.radioButton_44 = QtWidgets.QRadioButton(self.page_6)
        self.radioButton_44.setObjectName("radioButton_44")
        self.verticalLayout_7.addWidget(self.radioButton_44)
        self.radioButton_44.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_44.clicked.connect(lambda: save_all_from_cat(3,1))
        self.radioButton_44.clicked.connect(lambda: self.label_7.setText(label_text))

        self.radioButton_45 = QtWidgets.QRadioButton(self.page_6)
        self.radioButton_45.setObjectName("radioButton_45")
        self.radioButton_45.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_45.clicked.connect(lambda: save_all_from_cat(3,2))
        self.radioButton_45.clicked.connect(lambda: self.label_7.setText(label_text))
        self.verticalLayout_7.addWidget(self.radioButton_45)

        self.radioButton_46 = QtWidgets.QRadioButton(self.page_6)
        self.radioButton_46.setObjectName("radioButton_46")
        self.verticalLayout_7.addWidget(self.radioButton_46)
        self.radioButton_46.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_46.clicked.connect(lambda: save_all_from_cat(3,3))
        self.radioButton_46.clicked.connect(lambda: self.label_7.setText(label_text))
        self.verticalLayout_7.addWidget(self.radioButton_45)

        self.radioButton_47 = QtWidgets.QRadioButton(self.page_6)
        self.radioButton_47.setObjectName("radioButton_47")
        self.radioButton_47.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_47.clicked.connect(lambda: save_all_from_cat(3,4))
        self.radioButton_47.clicked.connect(lambda: self.label_7.setText(label_text))
        self.verticalLayout_7.addWidget(self.radioButton_47)

        
        self.radioButton_48 = QtWidgets.QRadioButton(self.page_6)
        self.radioButton_48.setObjectName("radioButton_48")
        self.radioButton_48.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_48.clicked.connect(lambda: save_all_from_cat(3,5))
        self.radioButton_48.clicked.connect(lambda: self.label_7.setText(label_text))
        self.verticalLayout_7.addWidget(self.radioButton_48)

        self.radioButton_49 = QtWidgets.QRadioButton(self.page_6)
        self.radioButton_49.setObjectName("radioButton_49")
        self.radioButton_49.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_49.clicked.connect(lambda: save_all_from_cat(3,6))
        self.radioButton_49.clicked.connect(lambda: self.label_7.setText(label_text))
        self.verticalLayout_7.addWidget(self.radioButton_49)

        self.radioButton_50 = QtWidgets.QRadioButton(self.page_6)
        self.radioButton_50.setObjectName("radioButton_50")
        self.radioButton_50.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_50.clicked.connect(lambda: save_all_from_cat(3,7))
        self.radioButton_50.clicked.connect(lambda: self.label_7.setText(label_text))
        self.verticalLayout_7.addWidget(self.radioButton_50)

        self.radioButton_51 = QtWidgets.QRadioButton(self.page_6)
        self.radioButton_51.setObjectName("radioButton_51")
        self.radioButton_51.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_51.clicked.connect(lambda: save_all_from_cat(3,8))
        self.radioButton_51.clicked.connect(lambda: self.label_7.setText(label_text))
        self.verticalLayout_7.addWidget(self.radioButton_51)

        self.radioButton_52 = QtWidgets.QRadioButton(self.page_6)
        self.radioButton_52.setObjectName("radioButton_52")
        self.radioButton_52.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_52.clicked.connect(lambda: save_all_from_cat(3,9))
        self.radioButton_52.clicked.connect(lambda: self.label_7.setText(label_text))
        self.verticalLayout_7.addWidget(self.radioButton_52)

        self.radioButton_53 = QtWidgets.QRadioButton(self.page_6)
        self.radioButton_53.setObjectName("radioButton_53")
        self.radioButton_53.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_53.clicked.connect(lambda: save_all_from_cat(3,10))
        self.radioButton_53.clicked.connect(lambda: self.label_7.setText(label_text))
        self.verticalLayout_7.addWidget(self.radioButton_53)

        self.radioButton_54 = QtWidgets.QRadioButton(self.page_6)
        self.radioButton_54.setObjectName("radioButton_54")
        self.radioButton_54.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_54.clicked.connect(lambda: save_all_from_cat(3,11))
        self.radioButton_54.clicked.connect(lambda: self.label_7.setText(label_text))
        self.verticalLayout_7.addWidget(self.radioButton_54)

        self.radioButton_55 = QtWidgets.QRadioButton(self.page_6)
        self.radioButton_55.setObjectName("radioButton_55")
        self.radioButton_55.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_55.clicked.connect(lambda: save_all_from_cat(3,12))
        self.radioButton_55.clicked.connect(lambda: self.label_7.setText(label_text))        
        self.verticalLayout_7.addWidget(self.radioButton_55)

        self.radioButton_56 = QtWidgets.QRadioButton(self.page_6)
        self.radioButton_56.setObjectName("radioButton_56")
        self.radioButton_56.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.radioButton_56.clicked.connect(lambda: save_all_from_cat(3,13))
        self.radioButton_56.clicked.connect(lambda: self.label_7.setText(label_text))
        self.verticalLayout_7.addWidget(self.radioButton_56)

        ################
        # Reading page #
        ################

        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_7)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollArea = QtWidgets.QScrollArea(self.page_7)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 418, 338))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7)
        self.radioButton_4.clicked.connect(lambda: self.label_7.setText(label_text))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_8.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.page_7)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pushButton_2 = QtWidgets.QPushButton(self.page)
        self.pushButton_2.setObjectName("home_button")
        self.statusbar.addWidget(self.pushButton_2)
        self.pushButton_2.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1))

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Enron Corpus Viewer"))
        self.label.setText(_translate("MainWindow", "Welcome to the Enron Corpus Viewer"))
        self.pushButton.setText(_translate("MainWindow", "Click here to start"))
        self.label_2.setText(_translate("MainWindow", "Select a primary category"))
        self.radioButton.setText(_translate("MainWindow", "Coarse Genre"))
        self.radioButton_2.setText(_translate("MainWindow", "Included / Forwarded Information"))
        self.radioButton_3.setText(_translate("MainWindow", "Emotional Tone (If Not Neutral)"))
        self.label_3.setText(_translate("MainWindow", "Coarse genre selected. \n"
"Now choose a secondary category"))
        self.radioButton_4.setText(_translate("MainWindow", "Company business, strategy, etc"))
        self.radioButton_5.setText(_translate("MainWindow", "Purely personal"))
        self.radioButton_6.setText(_translate("MainWindow", "Personal but in a professional context"))
        self.radioButton_7.setText(_translate("MainWindow", "Logistic arrangements"))
        self.radioButton_8.setText(_translate("MainWindow", "Employment arrangements"))
        self.radioButton_9.setText(_translate("MainWindow", "Document editing / checking"))
        self.radioButton_10.setText(_translate("MainWindow", "Empty message due to missing attatchement"))
        self.radioButton_11.setText(_translate("MainWindow", "Empty message"))
        self.label_4.setText(_translate("MainWindow", "Included / Forwarded Information \n"
"chosen. \n"
"Now choose a secondary category"))
        self.radioButton_12.setText(_translate("MainWindow", "Includes new text in addition to forwarded material"))
        self.radioButton_13.setText(_translate("MainWindow", "Forwarded email(s) including replies"))
        self.radioButton_14.setText(_translate("MainWindow", "Business letter(s) / document(s)"))
        self.radioButton_15.setText(_translate("MainWindow", "News article(s)"))
        self.radioButton_16.setText(_translate("MainWindow", "Government / academic report(s)"))
        self.radioButton_17.setText(_translate("MainWindow", "Government action(s)"))
        self.radioButton_18.setText(_translate("MainWindow", "Press releases"))
        self.radioButton_19.setText(_translate("MainWindow", "Legal documents"))
        self.radioButton_20.setText(_translate("MainWindow", "Pointers to URL(s)"))
        self.radioButton_21.setText(_translate("MainWindow", "Newsletters"))
        self.radioButton_22.setText(_translate("MainWindow", "Jokes / humour (related to business)"))
        self.radioButton_23.setText(_translate("MainWindow", "Jokes / humour (unrelated to business)"))
        self.radioButton_24.setText(_translate("MainWindow", "Attatchment(s) presumed missing"))
        self.label_5.setText(_translate("MainWindow", "Emotional Tone (If Not Neutral)"))
        self.radioButton_25.setText(_translate("MainWindow", "Jubilation"))
        self.radioButton_40.setText(_translate("MainWindow", "Anger / Agitation"))
        self.radioButton_26.setText(_translate("MainWindow", "Hope / Anticipation"))
        self.radioButton_41.setText(_translate("MainWindow", "Sadness / Despair"))
        self.radioButton_27.setText(_translate("MainWindow", "Humour"))
        self.radioButton_42.setText(_translate("MainWindow", "Shame"))
        self.radioButton_28.setText(_translate("MainWindow", "Camaraderie"))
        self.radioButton_43.setText(_translate("MainWindow", "Dislike / Scorn"))
        self.radioButton_29.setText(_translate("MainWindow", "Admiration"))
        self.radioButton_30.setText(_translate("MainWindow", "Gratitude"))
        self.radioButton_31.setText(_translate("MainWindow", "Friendship / Affection"))
        self.radioButton_32.setText(_translate("MainWindow", "Sympathy / Support"))
        self.radioButton_33.setText(_translate("MainWindow", "Sarcasm"))
        self.radioButton_34.setText(_translate("MainWindow", "Secrecy /Confidentiality"))
        self.radioButton_35.setText(_translate("MainWindow", "Worry / Anxiety"))
        self.radioButton_36.setText(_translate("MainWindow", "Concern"))
        self.radioButton_37.setText(_translate("MainWindow", "Competitiveness / Agressiveness"))
        self.radioButton_38.setText(_translate("MainWindow", "Triumph / Gloating"))
        self.radioButton_39.setText(_translate("MainWindow", "Pride"))
        self.label_6.setText(_translate("MainWindow", "Company Business, Strategy, Etc"))
        self.radioButton_44.setText(_translate("MainWindow", "Regulations and Regulators"))
        self.radioButton_45.setText(_translate("MainWindow", "Internal Proects - Progress and Strategy"))
        self.radioButton_46.setText(_translate("MainWindow", "Company Image - Current"))
        self.radioButton_47.setText(_translate("MainWindow", "Company Image - Changing / Influencing"))
        self.radioButton_48.setText(_translate("MainWindow", "Political Influence / Contributions / Contacts"))
        self.radioButton_49.setText(_translate("MainWindow", "California Energy Crisis / California Politics"))
        self.radioButton_50.setText(_translate("MainWindow", "Internal Company Policy"))
        self.radioButton_51.setText(_translate("MainWindow", "Internal Company Operations"))
        self.radioButton_52.setText(_translate("MainWindow", "Alliances / Partnerships"))
        self.radioButton_53.setText(_translate("MainWindow", "Legal Advice"))
        self.radioButton_54.setText(_translate("MainWindow", "Talking Points"))
        self.radioButton_55.setText(_translate("MainWindow", "Meeting Minutes"))
        self.radioButton_56.setText(_translate("MainWindow", "Trip Reports"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_2.setText(_translate("MainWindow", "Back"))

    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
